//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Upkeep_v3.Store_Attendance
{


    public partial class My_StoreOpeningClosing_Report
    {
    }
}
